project      = "helical-clock-463918-c9"
vm_name      = "dev-vm"
bucket_name  = "dev-bucket"
region       = "us-central1"
zone         = "us-central1-a"
machine_type = "e2-micro"
vm_image     = "debian-cloud/debian-11"
